services:
    tensorflow:
      build: .
      volumes:
        - ./data:/data
        - ./models:/models
        - ./notebooks:/notebooks
        - ./scripts:/scripts
      ports:
        - 8888:8888
      deploy:
        resources:
            reservations:
                devices:
                    - capabilities: [gpu]
      environment:
        NEPTUNE_API_TOKEN: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiOTZmZDczYmMtMGFmNi00ZTY2LWE3M2MtMDZmNzI3ZDFhMWVlIn0='
        NCCL_DEBUG: 'warn'
      shm_size: '2gb'
      command: jupyter lab --notebook-dir=/notebooks
