services:
    model-preparation:
      build: ./services/model-preparation/
      volumes:
        - ./data:/data
        - ./model:/model
        - ./automl:/automl
        - ./services/model-preparation/notebooks:/notebooks
        - ./services/model-preparation/scripts:/scripts
        - ./onnx:/onnx
      ports:
        - 8888:8888
      deploy:
        resources:
            reservations:
                devices:
                    - capabilities: [gpu]
      environment:
        NEPTUNE_API_TOKEN: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiOTZmZDczYmMtMGFmNi00ZTY2LWE3M2MtMDZmNzI3ZDFhMWVlIn0='
        NCCL_DEBUG: 'warn'
      shm_size: '2gb'
      command: jupyter lab --notebook-dir=/notebooks

    triton:
      container_name: triton
      image: nvcr.io/nvidia/tritonserver:21.02-py3
      restart: on-failure
      volumes:
          - ./onnx:/models
      deploy:
          resources:
              reservations:
                  devices:
                      - capabilities: [gpu]
      shm_size: '2gb'
      command: tritonserver --model-repository=/models
      healthcheck:
        test: ["CMD", "curl", "-f", "localhost:8000/v2/health/ready"]
        interval: 5s
        timeout: 5s
        retries: 10

    api:
      build: ./services/api/
      ports:
        - 5000:5000
